### ISSUE TITLE
Add linux & mac support

### ISSUE THREAD

**Issue by feliwir** [bazelregistry/sdl2#1]
Hello,
it would be great if you could finish the Linux & Mac support. Thanks!

**Comment by prestwood** [comment]
+1

This would be very useful. I want to try SDL2 on my Mac and this repo appears to only support Windows at the moment.

**Comment by zaucy** [comment]
I hear you guys loud and clear. I'll see what I can do. Don't expect anything too soon though.

**Comment by gaycodegal** [comment]
I'm currently working on compiling my own game with SDL2 and came across your project, and while it's not Mac it does support Windows, Linux, and Android currently so you're welcome to check out my BUILD/bzl files and compilation notes at https://github.com/gaycodegal/operator-12/blob/master/ANDROID.md for how I got that working. Linux support does require installing the dev libraries, windows requires downloading headers/includes & android does require downloading the sources for {SDL2,SDL2_image,SDL2_mixer,SDL2_ttf}. But hopefully helpful to you as i did find it a bit difficult to get working the first time. Feel free to take directly from my build files if useful. Will be working on Mac/iOS support next for my own project. Edit: to zaucy feel free to bother me on git or twitter (@gaycodegal) if you need help with android compilation.

**Comment by kazaamjt** [comment]
I tried compilation from source on linux (spend a whole weekend on it) but due way it's set up I keep running in to circular dependencies etc.
Getting that working is going to be a nightmare :/

For my own project I'm thinking of going the route of using using the makefile, as described [here](https://docs.bazel.build/versions/master/external.html#non-bazel-projects)

**Comment by kazaamjt** [comment]
@zaucy how do you feel about using bazel make rules?

**Comment by zaucy** [comment]
> I tried compilation from source on linux (spend a whole weekend on it) but due way it's set up I keep running in to circular dependencies etc.
Getting that working is going to be a nightmare :/

Yea it's a lot of work. Big reason why I haven't gotten to it.

> @zaucy how do you feel about using bazel make rules?

Bazel make rules? Are you referring to https://github.com/bazelbuild/rules_foreign_cc? If so I haven't used it before. It looks interesting.

Or are you saying creating a custom bazel rule for SDL2?

**Comment by kazaamjt** [comment]
I indeed meant rules_foreign_cc.
I've been playing around with it, and I got it mostly working, but I stumbled on to a slight issue:
I include the rules_foreign_cc in the SDL2 workspace, but it doesn't actually find them unless I include the http_archive in my own workspace. I would prefer it being as easy as adding sdl2 to deps.

**Comment by zaucy** [comment]
A lot of repositories have a macro for getting it's dependencies into the library consumers workspace. It could look something like this.

Library consumers `WORKSPACE` file:

```python
http_archive(
    name="some_sdl2_repository",
    # ...
)

load("@some_sdl2_repository//index.bzl;", "sdl2_dependencies")
sdl2_dependencies()

```

Then in `index.bzl` in the `@some_sdl2_repository` repository it could look like this:

```python
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def sdl2_dependencies():
    http_archive(
        name="some_dependency_that_some_sdl2_repository_needs",
        # ...
    )

    http_archive(
        name="another_dep_that_some_sdl2_repository_needs",
        # ...
    )
```

Does something like that work for you?

**Comment by gbuzogany** [comment]
I got it working on mac, but on my fork. I can merge the changes back here if you want.
https://github.com/gbuzogany/sdl2

**Comment by kazaamjt** [comment]
> 
> I got it working on mac, but on my fork. I can merge the changes back here if you want.
> https://github.com/gbuzogany/sdl2

Cool!

**Comment by kazaamjt** [comment]
> 
> Does something like that work for you?

Yes that worked, but I ran in to a host of other problems.
Seems that for Linux, there's always a new peril behind the corner.
I might just go back to what I was originally planning, even though that would take a while... But I think that's the best way of getting it done.

**Comment by gbuzogany** [comment]
Created a pull request that should add linux + macos support
#7
